package com.beertracker

import com.beertracker.domain.CatalogProduct
import com.beertracker.domain.TriedBeer

fun beer(
    id: String = "id",
    name: String = "Beer $id",
    brewery: String = "Brewery",
    type: String = "Lager",
    alcoholPercent: Double? = 5.0,
    volumeMl: Int? = 330,
    price: Double? = 25.0,
    grade: Int? = 4,
    tried: Boolean = true,
    note: String = "",
    aftertaste: String = "",
    goesWellWith: List<String> = emptyList(),
    buyAgain: Boolean = false,
    favourite: Boolean = false,
    dateAdded: Long = 0L,
    imageUrl: String? = null,
) = TriedBeer(
    id = id,
    name = name,
    brewery = brewery,
    type = type,
    alcoholPercent = alcoholPercent,
    volumeMl = volumeMl,
    price = price,
    grade = grade,
    tried = tried,
    note = note,
    aftertaste = aftertaste,
    goesWellWith = goesWellWith,
    buyAgain = buyAgain,
    favourite = favourite,
    dateAdded = dateAdded,
    catalogArticleNumber = null,
    addedBy = null,
    imageUrl = imageUrl,
)

fun catalogProduct(
    articleNumber: String = "1324515",
    articleNumberShort: String? = "13245",
    name: String = "Omnipollo Prodigal Pale Ale",
    brewery: String = "Omnipollo",
    type: String = "Ale",
    alcoholPercent: Double? = 5.2,
    volumeMl: Int? = 330,
    price: Double? = 25.9,
    country: String? = "Sverige",
    imageUrl: String? = "https://product-cdn.systembolaget.se/productimages/50786609/50786609",
) = CatalogProduct(
    articleNumber = articleNumber,
    articleNumberShort = articleNumberShort,
    name = name,
    brewery = brewery,
    type = type,
    alcoholPercent = alcoholPercent,
    volumeMl = volumeMl,
    price = price,
    country = country,
    imageUrl = imageUrl,
)
